version: '3.7'

services:
  frontend:
    container_name: cc-frontend-service
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
  backend:
    container_name: cc-backend-service
    build:
      context: .
      dockerfile: backend.Dockerfile
